# Generated by Django 2.1.7 on 2019-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(default='RoMa', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='example@princeton.edu', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Firstname Lastname', max_length=50),
        ),
    ]
