# Generated by Django 2.1.7 on 2019-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190422_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='piclink',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='tigerlink',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
