# Generated by Django 2.1.7 on 2019-04-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0003_group_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
