# Generated by Django 2.1.7 on 2019-04-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0004_auto_20190405_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='person', max_length=50),
        ),
    ]
