# Generated by Django 2.1.7 on 2019-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0006_auto_20190420_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='origin',
            field=models.CharField(default='PRINCETON', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='origin',
            field=models.CharField(default='PRINCETON', max_length=50),
        ),
    ]
