# Generated by Django 2.1.7 on 2019-04-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0007_auto_20190425_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
