# Generated by Django 2.1.7 on 2019-05-01 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0008_group_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(on_delete='CASCADE', related_name='comments', to='tigertravel.Group'),
        ),
    ]
