# Generated by Django 2.1.7 on 2019-05-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0009_auto_20190501_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='text',
            field=models.TextField(default='message'),
        ),
    ]
