# Generated by Django 2.1.7 on 2019-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0010_group_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ManyToManyField(to='tigertravel.Group'),
        ),
    ]
