# Generated by Django 2.1.7 on 2019-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigertravel', '0011_auto_20190502_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(to='tigertravel.Comment'),
        ),
    ]
